import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared";

const noto_sans = Noto_Sans({
  subsets: ["cyrillic"],
  variable: "--font-noto_sans",
  weight: ["400", "500", "600", "700", "800", "900"],
}); 

export const metadata: Metadata = {
  title: "Diving shop | Главная",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={noto_sans.className}>
        <main className="min-h-screen">
          <Header/>
          {children}</main>
      </body>
    </html>
  );
}
